const ACTION = {
  SET_PLAYER_NAME: 'SET_PLAYER_NAME',
  PLAYERSCORE: 'PLAYERSCORE',
  COMPUTERSCORE: 'COMPUTERSCORE',
  RESET_PLAYER_SCORE: 'RESET_PLAYER_SCORE',
  RESET_COMPUTER_SCORE: 'RESET_COMPUTER_SCORE',
  RESULT_WINNER: 'RESULT_WINNER',
  ALLOW_CLICK_ROCK: 'ALLOW_CLICK_ROCK',
  ALLOW_CLICK_PAPER: 'ALLOW_CLICK_PAPER',
  ALLOW_CLICK_SCISSOR: 'ALLOW_CLICK_SCISSOR',
  CLICK_ROCK: 'CLICK_ROCK',
  CLICK_PAPER: 'CLICK_PAPER',
  CLICK_SCISSOR: 'CLICK_SCISSOR',
  ROCK_SELECTED: 'ROCK_SELECTED',
  PAPER_SELECTED: 'PAPER_SELECTED',
  SCISSOR_SELECTED: 'SCISSOR_SELECTED',
  CURRENT_PLAYER: 'CURRENT_PLAYER',
  CURRENT_TEXT: 'CURRENT_TEXT',
  STORE_PLAYER_NAME: 'STORE_PLAYER_NAME'
};

export default ACTION;